# 端口号
server.port: 8081
# 服务名称
spring.application.name: service-gateway
# 注册中心
eureka.client.service-url.defaultZone: http://localhost:1001/eureka/

## 方式一：采用服务ID建立路由
#spring.cloud.gateway.discovery.locator.enabled: true #自动根据服务ID建立路由，路由的路径对应会使用大写ID
#spring.cloud.gateway.discovery.locator.lowerCaseServiceId: true #将路由路径改成小写ID
## 方式二：采用自定义路由（省略，本次采用actuator动态创建路由）
#spring.cloud.gateway.routes: 配置自定义路由

spring:
  redis:
    host: 127.0.0.1
    database: 0
    lettuce:
      pool:
        max-active: 300
        max-wait: -1s


# hystrix 信号量隔离，1.5秒后自动超时
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 1500



eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug

# Spring Cloud 执行器API是通过Actuator自定义控制器端点，他可以在网关已经启动的时候对网关的路径进行增删改操作
management.endpoint.gateway.enabled: true
management.endpoints.web.exposure.include: gateway