server:
  port: 1002

spring:
  application:
    name: eurka-server #应用名称（集群下相同）

eureka:
  instance:
    hostname: eureka02 #主机名，不配置时会根据操作系统的主机名来获取
    prefer-ip-address: true #是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    # 设置服务注册中心地址，指向另一个注册中心
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/