# 端口号
server.port: 2001
# 服务名
spring.application.name: admin-client

# 注册中心
eureka.client.service-url.defaultZone: ${EUREKA_SERVICE_URL:http://localhost:1001}/eureka/


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always